import XCTest
@testable import GhWallpaper

/// Asserts that `SVGBuilder.build(...)` produces byte-identical output to the
/// committed snapshots in `Tests/GhWallpaperTests/snapshots/` for every
/// (fixture × theme × canvas) combination. The committed snapshots are
/// generated by `swift run SnapshotGen` (or `script/refresh-snapshots.sh`).
///
/// When you make an intentional change to layout, glyph data, theme colors,
/// or any other input that legitimately alters the SVG, regenerate by either:
///   - `swift run SnapshotGen` (overwrites all snapshots), or
///   - `GH_WALLPAPER_UPDATE_SNAPSHOTS=1 swift test` (lets the test write the
///     observed output as the new snapshot, useful for CI-side regen).
///
/// Per SPEC §17 item 3, we deliberately do not snapshot rasterized PNGs —
/// resvg version drift produces sub-pixel differences that aren't
/// regressions. Text-diffing SVG keeps the signal clean.
final class SVGSnapshotTests: XCTestCase {

    private static let canvases: [(label: String, width: Int, height: Int)] = [
        ("2880x1800", 2880, 1800),
        ("5120x2880", 5120, 2880),
    ]

    private static let themes: [(label: String, theme: Theme)] = [
        ("github-dark", Themes.githubDark),
        ("github-light", Themes.githubLight),
        ("paper", Themes.paper),
        ("midnight", Themes.midnight),
        ("blossom", Themes.blossom),
        ("sunset", Themes.sunset),
        ("ocean", Themes.ocean),
        ("forest", Themes.forest),
    ]

    private static let fixtures = ["active", "sparse", "empty"]

    private let parser = HTMLParser()
    private let builder = SVGBuilder()

    private var updateSnapshots: Bool {
        ProcessInfo.processInfo.environment["GH_WALLPAPER_UPDATE_SNAPSHOTS"] == "1"
    }

    func testEveryFixtureThemeCanvasMatchesSnapshot() throws {
        for fixture in Self.fixtures {
            let calendar = try loadFixture(fixture)
            for (themeLabel, theme) in Self.themes {
                for canvas in Self.canvases {
                    try assertSnapshotMatches(
                        calendar: calendar,
                        theme: theme,
                        themeLabel: themeLabel,
                        canvasLabel: canvas.label,
                        canvasSize: SVGBuilder.Canvas(
                            widthPx: canvas.width,
                            heightPx: canvas.height
                        ),
                        fixture: fixture
                    )
                }
            }
        }
    }

    // MARK: - Helpers

    private func loadFixture(_ name: String) throws -> ContributionCalendar {
        let path = Bundle.module.path(forResource: name, ofType: "html", inDirectory: "fixtures")
                ?? Bundle.module.path(forResource: name, ofType: "html")
        let resolved = try XCTUnwrap(path, "fixture \(name).html not found")
        let html = try String(contentsOfFile: resolved, encoding: .utf8)
        let days = try parser.parse(html: html)
        return ContributionCalendar(username: name, days: days)
    }

    private func snapshotURL(fixture: String, theme: String, canvas: String) -> URL? {
        let name = "\(fixture)-\(theme)-\(canvas)"
        return Bundle.module.url(forResource: name, withExtension: "svg", subdirectory: "snapshots")
            ?? Bundle.module.url(forResource: name, withExtension: "svg")
    }

    private func assertSnapshotMatches(
        calendar: ContributionCalendar,
        theme: Theme,
        themeLabel: String,
        canvasLabel: String,
        canvasSize: SVGBuilder.Canvas,
        fixture: String,
        file: StaticString = #file,
        line: UInt = #line
    ) throws {
        let actual = builder.build(calendar: calendar, theme: theme, canvas: canvasSize)
        guard let url = snapshotURL(fixture: fixture, theme: themeLabel, canvas: canvasLabel) else {
            XCTFail(
                """
                missing snapshot for \(fixture)-\(themeLabel)-\(canvasLabel).
                Regenerate with: swift run SnapshotGen
                """,
                file: file, line: line
            )
            return
        }

        if updateSnapshots {
            try actual.write(to: url, atomically: true, encoding: .utf8)
            return
        }

        let expected = try String(contentsOf: url, encoding: .utf8)
        if actual != expected {
            // Surface a compact, actionable diff hint instead of dumping
            // hundreds of lines of SVG.
            let actualBytes = actual.utf8.count
            let expectedBytes = expected.utf8.count
            XCTFail(
                """
                SVG snapshot mismatch: \(fixture)-\(themeLabel)-\(canvasLabel)
                  actual: \(actualBytes) bytes
                  expected: \(expectedBytes) bytes
                Inspect the diff at \(url.path), then either:
                  - revert your change, or
                  - intentionally regenerate via `swift run SnapshotGen` and
                    review the diff in your PR.
                """,
                file: file, line: line
            )
        }
    }
}
